'use strict';

const { app, assert } = require('egg-mock/bootstrap');

describe('test/app/service/repos.test.js', () => {

  describe('createFromGithubAPI', () => {
    it('should work', async () => {
      const ctx = app.mockContext({});
      const data = {
        id: 134475380,
        node_id: 'MDEwOlJlcG9zaXRvcnkxMzQ0NzUzODA=',
        name: 'repl',
        full_name: 'nodejs/repl',
        private: false,
        owner: {
          login: 'nodejs',
          id: 9950313,
          node_id: 'MDEyOk9yZ2FuaXphdGlvbjk5NTAzMTM=',
          avatar_url: 'https://avatars3.githubusercontent.com/u/9950313?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/nodejs',
          html_url: 'https://github.com/nodejs',
          followers_url: 'https://api.github.com/users/nodejs/followers',
          following_url: 'https://api.github.com/users/nodejs/following{/other_user}',
          gists_url: 'https://api.github.com/users/nodejs/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/nodejs/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/nodejs/subscriptions',
          organizations_url: 'https://api.github.com/users/nodejs/orgs',
          repos_url: 'https://api.github.com/users/nodejs/repos',
          events_url: 'https://api.github.com/users/nodejs/events{/privacy}',
          received_events_url: 'https://api.github.com/users/nodejs/received_events',
          type: 'Organization',
          site_admin: false,
        },
        html_url: 'https://github.com/nodejs/repl',
        description: 'REPL rewrite for Node.js ✨🐢🚀✨',
        fork: false,
        url: 'https://api.github.com/repos/nodejs/repl',
        forks_url: 'https://api.github.com/repos/nodejs/repl/forks',
        keys_url: 'https://api.github.com/repos/nodejs/repl/keys{/key_id}',
        collaborators_url: 'https://api.github.com/repos/nodejs/repl/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/nodejs/repl/teams',
        hooks_url: 'https://api.github.com/repos/nodejs/repl/hooks',
        issue_events_url: 'https://api.github.com/repos/nodejs/repl/issues/events{/number}',
        events_url: 'https://api.github.com/repos/nodejs/repl/events',
        assignees_url: 'https://api.github.com/repos/nodejs/repl/assignees{/user}',
        branches_url: 'https://api.github.com/repos/nodejs/repl/branches{/branch}',
        tags_url: 'https://api.github.com/repos/nodejs/repl/tags',
        blobs_url: 'https://api.github.com/repos/nodejs/repl/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/nodejs/repl/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/nodejs/repl/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/nodejs/repl/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/nodejs/repl/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/nodejs/repl/languages',
        stargazers_url: 'https://api.github.com/repos/nodejs/repl/stargazers',
        contributors_url: 'https://api.github.com/repos/nodejs/repl/contributors',
        subscribers_url: 'https://api.github.com/repos/nodejs/repl/subscribers',
        subscription_url: 'https://api.github.com/repos/nodejs/repl/subscription',
        commits_url: 'https://api.github.com/repos/nodejs/repl/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/nodejs/repl/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/nodejs/repl/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/nodejs/repl/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/nodejs/repl/contents/{+path}',
        compare_url: 'https://api.github.com/repos/nodejs/repl/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/nodejs/repl/merges',
        archive_url: 'https://api.github.com/repos/nodejs/repl/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/nodejs/repl/downloads',
        issues_url: 'https://api.github.com/repos/nodejs/repl/issues{/number}',
        pulls_url: 'https://api.github.com/repos/nodejs/repl/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/nodejs/repl/milestones{/number}',
        notifications_url: 'https://api.github.com/repos/nodejs/repl/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/nodejs/repl/labels{/name}',
        releases_url: 'https://api.github.com/repos/nodejs/repl/releases{/id}',
        deployments_url: 'https://api.github.com/repos/nodejs/repl/deployments',
        created_at: '2018-05-22T21:00:45Z',
        updated_at: '2019-01-18T18:30:31Z',
        pushed_at: '2019-01-03T20:01:18Z',
        git_url: 'git://github.com/nodejs/repl.git',
        ssh_url: 'git@github.com:nodejs/repl.git',
        clone_url: 'https://github.com/nodejs/repl.git',
        svn_url: 'https://github.com/nodejs/repl',
        homepage: '',
        size: 140,
        stargazers_count: 28,
        watchers_count: 28,
        language: 'JavaScript',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        forks_count: 9,
        mirror_url: null,
        archived: false,
        open_issues_count: 9,
        license: {
          key: 'mit',
          name: 'MIT License',
          spdx_id: 'MIT',
          url: 'https://api.github.com/licenses/mit',
          node_id: 'MDc6TGljZW5zZTEz',
        },
        forks: 9,
        open_issues: 9,
        watchers: 28,
        default_branch: 'master',
        organization: {
          login: 'nodejs',
          id: 9950313,
          node_id: 'MDEyOk9yZ2FuaXphdGlvbjk5NTAzMTM=',
          avatar_url: 'https://avatars3.githubusercontent.com/u/9950313?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/nodejs',
          html_url: 'https://github.com/nodejs',
          followers_url: 'https://api.github.com/users/nodejs/followers',
          following_url: 'https://api.github.com/users/nodejs/following{/other_user}',
          gists_url: 'https://api.github.com/users/nodejs/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/nodejs/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/nodejs/subscriptions',
          organizations_url: 'https://api.github.com/users/nodejs/orgs',
          repos_url: 'https://api.github.com/users/nodejs/repos',
          events_url: 'https://api.github.com/users/nodejs/events{/privacy}',
          received_events_url: 'https://api.github.com/users/nodejs/received_events',
          type: 'Organization',
          site_admin: false,
        },
        network_count: 9,
        subscribers_count: 9,
      };
      const res = await ctx.service.repos.createFromGithubAPI(0, data);
      assert(res.login === data.login);
      const res2 = await ctx.service.repos.createFromGithubAPI(0, data);
      assert(res2 === false);
    });
  });
});
